/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all events */
        get: operations["EventsController_findAll"];
        put?: never;
        /** Create an event (ORGANIZER or ADMIN) */
        post: operations["EventsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event by slug */
        get: operations["EventsController_findOne"];
        put?: never;
        post?: never;
        /** Delete an event (organizer or ADMIN) */
        delete: operations["EventsController_remove"];
        options?: never;
        head?: never;
        /** Update an event (organizer or ADMIN) */
        patch: operations["EventsController_update"];
        trace?: never;
    };
    "/events/{slug}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register for an event */
        post: operations["EventsController_register"];
        /** Cancel event registration */
        delete: operations["EventsController_cancelRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List event registrations (organizer or ADMIN) */
        get: operations["EventsController_getRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all gyms */
        get: operations["GymsController_findAll"];
        put?: never;
        /** Create a gym (GYM_OWNER or ADMIN) */
        post: operations["GymsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a gym by slug */
        get: operations["GymsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a gym (owner or ADMIN) */
        delete: operations["GymsController_remove"];
        options?: never;
        head?: never;
        /** Update a gym (owner or ADMIN) */
        patch: operations["GymsController_update"];
        trace?: never;
    };
    "/gyms/{slug}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a gym */
        post: operations["GymsController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gym members (owner or ADMIN) */
        get: operations["GymsController_getMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{slug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve, reject, or upgrade a member (owner or ADMIN) */
        patch: operations["GymsController_updateMember"];
        trace?: never;
    };
    "/gyms/{slug}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave a gym */
        delete: operations["GymsController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's gym memberships */
        get: operations["UsersController_getMyMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's event registrations */
        get: operations["UsersController_getMyRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gyms owned by the current user */
        get: operations["UsersController_getMyGyms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/gym-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending membership requests for gyms owned by the current user */
        get: operations["UsersController_getPendingRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive a JWT token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateEventDto: {
            /** @example Belgrade Open BJJ 2026 */
            title: string;
            /** @example Annual open BJJ tournament for all belt levels. */
            description: string;
            /** @example BJJ */
            discipline: string;
            /** @example Belgrade */
            city: string;
            /**
             * @description ISO 8601 date-time string
             * @example 2026-06-15T10:00:00.000Z
             */
            date: string;
            /** @example https://example.com/event-poster.jpg */
            poster: string;
            /** @example Sportski centar Olimp, hala 3 */
            address?: string;
            /**
             * @description Max attendees. Omit for unlimited.
             * @example 200
             */
            capacity?: number;
            /**
             * @description ISO 8601. Omit to keep registration open until event date.
             * @example 2026-06-10T23:59:00.000Z
             */
            registrationDeadline?: string;
            /**
             * @description UUID of the gym hosting this event
             * @example a1b2c3d4-...
             */
            gymId?: string;
        };
        EventResponseDto: {
            /** @example a1b2c3d4-... */
            id: string;
            /** @example belgrade-open-bjj-2026 */
            slug: string;
            /** @example Belgrade Open BJJ 2026 */
            title: string;
            /** @example BJJ */
            discipline: string;
            /** @example Belgrade */
            city: string;
            /** @example 2026-06-15T10:00:00.000Z */
            date: string;
            /** @example https://example.com/poster.jpg */
            poster: string;
            /** @example Annual open BJJ tournament for all belt levels. */
            description: string;
            /** @example Sportski centar Olimp, hala 3 */
            address: string | null;
            /** @example 200 */
            capacity: number | null;
            /** @example 1500.00 */
            price: string | null;
            /**
             * @example PUBLISHED
             * @enum {string}
             */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** @example 2026-06-10T23:59:00.000Z */
            registrationDeadline: string | null;
            /** @example a1b2c3d4-... */
            organizerId: string;
            /** @example a1b2c3d4-... */
            gymId: string | null;
            /** @example 2026-05-01T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-01T00:00:00.000Z */
            updatedAt: string;
        };
        UpdateEventDto: {
            /** @example Belgrade Open BJJ 2026 */
            title?: string;
            /** @example Annual open BJJ tournament for all belt levels. */
            description?: string;
            /** @example BJJ */
            discipline?: string;
            /** @example Belgrade */
            city?: string;
            /**
             * @description ISO 8601 date-time string
             * @example 2026-06-15T10:00:00.000Z
             */
            date?: string;
            /** @example https://example.com/event-poster.jpg */
            poster?: string;
            /** @example Sportski centar Olimp, hala 3 */
            address?: string;
            /**
             * @description Max attendees. Omit for unlimited.
             * @example 200
             */
            capacity?: number;
            /**
             * @description ISO 8601. Omit to keep registration open until event date.
             * @example 2026-06-10T23:59:00.000Z
             */
            registrationDeadline?: string;
            /**
             * @description UUID of the gym hosting this event
             * @example a1b2c3d4-...
             */
            gymId?: string;
        };
        GymResponseDto: {
            /** @example a1b2c3d4-... */
            id: string;
            /** @example elite-mma-belgrade */
            slug: string;
            /** @example Elite MMA Belgrade */
            name: string;
            /** @example Top-tier MMA training in the heart of Belgrade. */
            description: string;
            /** @example https://example.com/poster.jpg */
            poster: string;
            /**
             * @example [
             *       "MMA",
             *       "BJJ"
             *     ]
             */
            badges: string[];
            /** @example Knez Mihailova 1 */
            address: string | null;
            /** @example Belgrade */
            city: string | null;
            /** @example +381 11 123 4567 */
            phone: string | null;
            /** @example @elitemma */
            instagram: string | null;
            /** @example https://elitemma.rs */
            website: string | null;
            /** @example 44.8178 */
            latitude: number | null;
            /** @example 20.4569 */
            longitude: number | null;
            /** @example false */
            verified: boolean;
            /** @example false */
            requiresApproval: boolean;
            /** @example a1b2c3d4-... */
            ownerId: string;
            /** @example 2026-05-01T00:00:00.000Z */
            createdAt: string;
            /** @example 2026-05-01T00:00:00.000Z */
            updatedAt: string;
        };
        CreateGymDto: {
            /** @example Elite MMA Belgrade */
            name: string;
            /** @example Top-tier MMA training in the heart of Belgrade. */
            description: string;
            /**
             * @description Direct URL to the gym poster image
             * @example https://example.com/gym.jpg
             */
            poster: string;
            /**
             * @example [
             *       "MMA",
             *       "BJJ"
             *     ]
             */
            badges?: string[];
            /** @example Knez Mihailova 1 */
            address?: string;
            /** @example Belgrade */
            city?: string;
            /** @example +381 11 123 4567 */
            phone?: string;
            /** @example @elitemma */
            instagram?: string;
            /** @example https://elitemma.rs */
            website?: string;
            /**
             * @description If true, members require owner approval to join
             * @example false
             */
            requiresApproval?: boolean;
        };
        UpdateGymDto: {
            /** @example Elite MMA Belgrade */
            name?: string;
            /** @example Top-tier MMA training in the heart of Belgrade. */
            description?: string;
            /**
             * @description Direct URL to the gym poster image
             * @example https://example.com/gym.jpg
             */
            poster?: string;
            /**
             * @example [
             *       "MMA",
             *       "BJJ"
             *     ]
             */
            badges?: string[];
            /** @example Knez Mihailova 1 */
            address?: string;
            /** @example Belgrade */
            city?: string;
            /** @example +381 11 123 4567 */
            phone?: string;
            /** @example @elitemma */
            instagram?: string;
            /** @example https://elitemma.rs */
            website?: string;
            /**
             * @description If true, members require owner approval to join
             * @example false
             */
            requiresApproval?: boolean;
        };
        UpdateMembershipDto: {
            /**
             * @example APPROVED
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            /**
             * @example TRAINER
             * @enum {string}
             */
            role?: "MEMBER" | "TRAINER";
        };
        MeResponseDto: {
            /** @example a1b2c3d4-... */
            id: string;
            /** @example fighter@example.com */
            email: string;
            /**
             * @example GYM_OWNER
             * @enum {string}
             */
            role: "USER" | "GYM_OWNER" | "ORGANIZER" | "ADMIN";
        };
        RegisterDto: {
            /** @example fighter@example.com */
            email: string;
            /**
             * @description Min 8 chars, 1 uppercase, 1 number, 1 symbol
             * @example StrongPass1!
             */
            password: string;
            /** @example Marko Petrovic */
            name: string;
            /**
             * @description Self-assignable roles only. ORGANIZER and ADMIN are admin-assigned.
             * @example GYM_OWNER
             * @enum {string}
             */
            role?: "USER" | "GYM_OWNER";
        };
        AuthTokenResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
        };
        LoginDto: {
            /** @example fighter@example.com */
            email: string;
            /** @example StrongPass1! */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"][];
                };
            };
        };
    };
    EventsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"];
                };
            };
        };
    };
    EventsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"];
                };
            };
        };
    };
    EventsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"];
                };
            };
        };
    };
    EventsController_register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_cancelRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_getRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymResponseDto"][];
                };
            };
        };
    };
    GymsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGymDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymResponseDto"];
                };
            };
        };
    };
    GymsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymResponseDto"];
                };
            };
        };
    };
    GymsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGymDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymResponseDto"];
                };
            };
        };
    };
    GymsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymsController_getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymsController_updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GymsController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMyMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMyRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMyGyms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getPendingRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponseDto"];
                };
            };
        };
    };
}
